Handle default being easy
At some point the build environment also moved to easy mode, so the
check was doing absolutely nothing. Change logic to test secure
and paranoid mode and expect easy.

diff --git a/checks/50-check-permissions b/checks/50-check-permissions
--- a/checks/50-check-permissions
+++ b/checks/50-check-permissions
@@ -7,30 +7,49 @@ test -f $BUILD_ROOT/etc/sysconfig/security || exit 0
 
 HAD_ERRORS=0
 
+grep -q "easy local" $BUILD_ROOT/etc/sysconfig/security || {
+    echo "ERROR: expected permission level to be set to easy ?!"
+    HAD_ERRORS=1
+}
+
 RPM="chroot $BUILD_ROOT rpm --nodigest --nosignature -Vp --nofiledigest --nodeps"
 
 for i in $(find $BUILD_ROOT$TOPDIR/RPMS -type f -name "*.rpm" | sort) ; do
-    $RPM ${i#$BUILD_ROOT} > $BUILD_ROOT/.build_rpmVp_old
-    sed -i.bak -e "s@^PERMISSION_SECURITY\(.*\)secure@PERMISSION_SECURITY\1easy@" \
-	    $BUILD_ROOT/etc/sysconfig/security
-    chroot $BUILD_ROOT /usr/bin/chkstat --system >/dev/null 2>&1
-    $RPM ${i#$BUILD_ROOT} > $BUILD_ROOT/.build_rpmVp_new
+    case "$pkg" in
+        *-debuginfo-*|*-debugsource-*) continue ;;
+    esac
+    $RPM ${i#$BUILD_ROOT} > $BUILD_ROOT/.build_rpmVp_orig
+    sed -i.bak -e "s@^PERMISSION_SECURITY\(.*\)@PERMISSION_SECURITY = \"secure local\"@" \
+           $BUILD_ROOT/etc/sysconfig/security
+    chroot $BUILD_ROOT /usr/bin/chkstat --set --system >/dev/null 2>&1
+    $RPM ${i#$BUILD_ROOT} > $BUILD_ROOT/.build_rpmVp_secure
+    sed -i -e "s@^PERMISSION_SECURITY\(.*\)@PERMISSION_SECURITY = \"paranoid local\"@" \
+           $BUILD_ROOT/etc/sysconfig/security
+    chroot $BUILD_ROOT /usr/bin/chkstat --set --system >/dev/null 2>&1
+    $RPM ${i#$BUILD_ROOT} > $BUILD_ROOT/.build_rpmVp_paranoid
     mv $BUILD_ROOT/etc/sysconfig/security.bak $BUILD_ROOT/etc/sysconfig/security
-    chroot $BUILD_ROOT /usr/bin/chkstat --system >/dev/null 2>&1
-
-    if ! cmp -s $BUILD_ROOT/.build_rpmVp_old $BUILD_ROOT/.build_rpmVp_new; then
+    chroot $BUILD_ROOT /usr/bin/chkstat --set --system >/dev/null 2>&1
+    if ! cmp -s $BUILD_ROOT/.build_rpmVp_orig $BUILD_ROOT/.build_rpmVp_secure; then
 	echo "--------------------------------------------------------------------"
-	echo "package: $(rpm --nodigest --nosignature -qp --qf '%{NAME}' \"$i\")"
-	echo "/usr/bin/chkstat modified files that are not properly handled!"
-	echo "this will break rpm -V, ask ro for details."
+	echo "ERROR: chkstat --level secure modified package $(rpm --nodigest --nosignature -qp --qf '%{NAME}' \"$i\")"
+	echo "Please add '%verify(not mode,...) for those to avoid listings in rpm -V."
 	echo "diff for both runs of rpm -V:"
-	diff -u0 "$BUILD_ROOT/.build_rpmVp_old" "$BUILD_ROOT/.build_rpmVp_new"
+	diff -u0 "$BUILD_ROOT/.build_rpmVp_orig" "$BUILD_ROOT/.build_rpmVp_secure"
+	echo "--------------------------------------------------------------------"
+	HAD_ERRORS=1
+    fi
+    if ! cmp -s $BUILD_ROOT/.build_rpmVp_orig $BUILD_ROOT/.build_rpmVp_paranoid; then
+	echo "--------------------------------------------------------------------"
+        echo "ERROR: chkstat --level paranoid modified package $(rpm --nodigest --nosignature -qp --qf '%{NAME}' \"$i\")"
+        echo "Please add '%verify(not mode,...) for those to avoid listings in rpm -V."
+	echo "diff for both runs of rpm -V:"
+	diff -u0 "$BUILD_ROOT/.build_rpmVp_orig" "$BUILD_ROOT/.build_rpmVp_paranoid"
 	echo "--------------------------------------------------------------------"
 	HAD_ERRORS=1
     fi
 done
 
-rm -f $BUILD_ROOT/.build_rpmVp_old $BUILD_ROOT/.build_rpmVp_new
+rm -f $BUILD_ROOT/.build_rpmVp_{orig,secure,paranoid}
 
 if test "$HAD_ERRORS" = 1 ; then
 	touch $BUILD_ROOT/not-ready
